import "./globals.css";
import Header from "./Component/Header";
import Footer from "./Component/Footer";
import { AuthContextProvider } from "./context/AuthContext";
import { ToastContainer } from "react-toastify";

export const metadata = {
  title: "Knižničný systém",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        // className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
      <AuthContextProvider>
        <Header />
        {children}
        <ToastContainer
          theme="dark"
          position="top-right"
          autoClose={5000}
          closeOnClick
          pauseOnHover={false}
        />
        <Footer/>
      </AuthContextProvider>
      </body>
    </html>
  );
}
